module.exports = {
  appName: 'LoopVn',
  recentTitle: 'Bài luyện gần nhất',
  practiceTitle: 'Hoàn thành bài luyện',
  wholeProcess: 'Toàn bộ tiến trình',
  accurateSpeed: 'Tốc độ chính xác',
  text_description_complate: 'Bài thi đã hoàn thành. Dù kết quả ra sao bạn cũng đã cố gắng hết sức rồi!',
  text_description_noncomplate: 'Mỗi bài thi vượt qua khẳng định thêm hiểu biết của chúng ta về thế giới. Chúng ta cùng bắt tay vào làm bài thi nào!',
  description: 'Đã hết thời gian làm bài. Hãy bấm kết thúc để xem kết quả.',
  description1: 'Bạn cần hoàn thành 2/3 thời gian.',
  description2: `Bạn cần hoàn thành 2/3 thời gian để có thể nộp bài. Bấm thoát để trở về (Lưu ý bài thi chưa được nộp).`,
  description_competition: 'Hãy bình tĩnh, cẩn thận và làm bài một cách thông minh bạn nhé.',
  description_noncompetition: 'Bài thi vẫn chưa được hoàn thành. Bạn hãy tiếp tục hoàn thành nó nhé.',
  descriptionIntro1: 'Ứng dụng học tập từ lớp 1 - lớp 12, bao gồm tất cả các nội dung chương trình của Bộ và các kỳ thi.',
  descriptionIntro2: 'Học các bài học mới thông qua video, tham dự Lớp học online để tương tác với gia sư. Xem bài giảng và đọc các Khái niệm để sửa đổi và củng cố kiến ​​thức cơ bản.',
  descriptionIntro3: 'Bạn đang có một thắc mắc vào giữa đêm? Bạn có thể giải quyết nó ngay lập tức.',
  descriptionIntro4: 'Giải thử tất cả các bài kiểm tra, các mẫu đề thi hoặc tự mình tạo một bài kiểm tra và thi đua cùng bạn bè.',
  descriptionIntro5: 'Hệ thống sử dụng thuật toán thông minh để xây dựng bài luyện phù hợp cho từng học sinh dựa trên lịch sử ôn luyện.',
  descriptionContactForm: 'Hãy gọi cho chúng tôi',
  descriptionContactForm1: 'Gọi cho chúng tôi để giải đáp thắc mắc từ 8h sáng đến 21h tối.',
  numberPhone: '096.960.2660',
  descriptionPracticeModal: 'Bạn hãy cố gắng hoàn thành bài luyện tập để đạt được kiến thức',
  descriptionPracticeModal1: 'Bài luyện đã kết thúc',
  descriptionPracticeModal2: 'Bài luyện chưa được hoàn thành !',
  descriptionPauseModal: 'Bạn có muốn vượt qua bài luyện tập thêm một lần nữa ?',
  descriptionPauseModal1: 'Bạn cần cố gắng cho đến khi đạt mốc 100 %',
  descriptionTestPauseModal: 'Thời gian đã hết. Hãy bấm kết thúc để xem kết quả bài làm của bạn',
  descriptionTestPauseModal1: 'Thời gian vẫn còn. Bạn vẫn có thể kiểm tra lại',
  descriptionUpgradeScreen: '1 Môn Học',
  descriptionUpgradeScreen1: '199K',
  descriptionUpgradeScreen2: 'Hạn sử dụng đến tháng 06/2020',
  descriptionUpgradeScreen3: 'Luyện tập theo dạng môn học đăng ký',
  descriptionUpgradeScreen4: '- Nội dung bám sát kiến thức trên lớp',
  descriptionUpgradeScreen5: '- Cá nhân hóa bài luyện',
  descriptionUpgradeScreen6: '- Luyện tập kiến thức môn học các lớp trong cấp (Tiểu học, THCS, THPT)',
  descriptionUpgradeScreen7: 'Thi thử và luyện tâm lý phòng thi',
  descriptionUpgradeScreen8: '- Luyện đề bám sát mục tiêu kiểm tra 15 phút, 1 tiết, học kỳ và kỳ thi THPTQG',
  descriptionUpgradeScreen9: '- Đề thi theo ma trận chuẩn của bộ giáo dục, các đề thi thử từ các trường nổi tiếng trên toàn quốc',
  descriptionUpgradeScreen10: 'Báo cáo học tập thông minh',
  descriptionUpgradeScreen11: '- Báo Cáo mức độ thấu triệt của môn mình đăng ký',
  descriptionUpgradeScreen12: '- Đề xuất bài luyện nên học',
  descriptionUpgradeScreen13: 'Đăng ký',
  descriptionUpgradeScreen14: 'Tất cả các môn',
  descriptionUpgradeScreen15: '899K',
  // description for CompetitionPause Screen
  descriptionCompetitionPause: 'Hiện chưa đến giờ thi. Em hãy quay lại vào đúng giờ thi.',
  txtLabelNote: 'Trước khi làm bài các em chú ý tuân thủ quy định sau :',
  txtLabelNote1: '- Sau khi hết 2/3 thời gian làm bài, em mới được nộp bài kiểm tra.',
  txtLabelNote2: '- Em phải nhấn vào nút “Nộp bài" để hoàn thành bài kiểm tra.',
  txtLabelNote3: '- Hãy gọi hotline 0969.602.660 (nhánh số 1) nếu em cần hỗ trợ về mặt kỹ thuật.',
  txtLabelNote4: 'Bạn đã hoàn thành bài thi ',
  txtLabelNote5: 'Thời gian làm bài đã hết',
  txtLabelNote6: 'Sau khi nộp bài bạn không thể làm lại bài thi. Bạn có chắc chắn muốn nộp? ',
  txtLabelNote7: 'Bài thi vẫn chưa được nộp, bạn có chắc muốn thoát khỏi bài thi không? ',
  txtLabelNote8: 'Bạn phải làm hết 2/3 thời gian mới được phép nộp bài !',
  txtLabelNote9: `Bạn có chắc chắn muốn nộp? `,
  // description for SchoolPause screen
  descriptionSchoolPause: 'Bài tự luyện đã được hoàn thành.',
  descriptionSchoolPause1: 'Bài tự luyện vẫn chưa được hoàn thành. Bạn hãy cố gắng hoàn thành bài tự luyện nhé.',
  descriptionSchoolPause2: 'Hãy bình tĩnh, cẩn thận và làm bài một cách thông minh bạn nhé.',
  descriptionSchoolPause3: 'Bài kiểm tra đã được hoàn thành.',
  descriptionSchoolPause4: 'Bài kiểm tra vẫn chưa được hoàn thành. Bạn hãy cố gắng hoàn thành bài kiểm tra nhé.',
  descriptionSchoolPause5: 'Dạng bài thi này đang được phát triển',
  // description for SchoolResultTab screen
  descriptionSchoolResultTab: 'Bạn chỉ có thể xem lại sau khi hết hạn nộp bài',
  // description for AssignmentPause screen
  descriptionAssignmentPause: 'Bài tập chưa được hoàn thành. Bấm bắt đầu để làm bài.',
  descriptionAssignmentPause1: 'Gửi bài để chấm điểm.',
  descriptionAssignmentPause2: 'Bài làm đã được hoàn thành.',
  descriptionAssignmentPause3: 'Tạm dừng không được làm tiếp.',
  descriptionAssignmentPause4: 'Bài kiểm tra đã hết hạn làm bài. Bạn hãy thử các bài kiểm tra khác nhé.',

  exactly: 'Exactly',
  speed: 'Speed',
  timeP: 'TimeP',
  numFalse: 'NumFalse',
  numTrue: 'NumTrue',
  skip: 'Skip',
  percent_completed: 'percent_completed',
  mathID: 'TOAN',
  mathThID: 'TOANTHCS',
  mathThptID: 'TOANTHPT',
  mathHH: 'HOCHAY',
  mathVao10ID: 'TOANVAO10',
  mathPlayID: 'MATHPLAY',
  mathJRID: 'TOAN-JR',

  phyID: 'VATLY',
  phyTHCSID: 'VATLITHCS',
  phyThID: 'VATLITHCS',

  chemID: 'HOAHOC',
  chemThID: 'HOAHOCTHCS',

  bioID: 'SINH',

  literID: 'NGUVAN',
  literIDTHCS: 'NGUVANTHCS',

  hisID: 'LICHSU',
  hisTHID: 'LICHSUTHCS',

  geoID: 'DIALY',
  geoTHID: 'DIALITHCS',

  engID: 'TIENGANH',
  engID2: 'ANH',

  engTHPTID: 'ANHTHPT',
  engTHPT2: 'ANHTHPT2',
  engTHPT3: 'TIENGANHTHPT3',
  engGRM: 'ANHGENERAL',
  engTHCS: 'ANHTHCS',

  gdcdID: 'GDCD',
  gdcdTHID: 'GDCDTHCS',

  tinhocID: "TINHOC",
  stemID: 'STEM',
  amnhacID: 'AMNHAC',
  gdqpID: "GDQP",
  congngheID: "CONGNGHE",
  mythuatID: "MYTHUAT",
  gdtcID: "GDTC",
  tinhocID: "TINHOC",
  lienmonhocID: "LIENMONHOC",

  khoahocID: "STEM",

  mythuatID: 'MYTHUAT',

  amnhacID: 'AMNHAC',

  apiKeyYoutube: 'AIzaSyDczErB0NZ2yQxjv_wa_sz4ckJAVMo0Vso',
  practiceModal: 'practice-modal',
  type_home_list: 'type_home_list',
  type_exam_list: 'type_exam_list',
  type_sla_list: 'type_sla_list',
  type_sla_problem_list: 'type_sla_problem_list',
  test_app_component: false,
  urlMockExam: 'https://s3-ap-southeast-1.amazonaws.com/onluyen-mock-test/test/',

};

