export const DISPLAY_PACKAGE_MODAL_ACTION = 'DISPLAY_PACKAGE_MODAL_ACTION';
export const DISPLAY_INPUT_PHONE_ACTION = 'DISPLAY_INPUT_PHONE_ACTION';
export const DISPLAY_WARNING_MODAL_ACTION = 'DISPLAY_WARNING_MODAL_ACTION';
export const DISPLAY_RESULT_CONFIRM_ACTION = 'DISPLAY_RESULT_CONFIRM_ACTION';
export const FETCH_LIST_CHAPTER_START_ACTION = 'FETCH_LIST_CHAPTER_START_ACTION';
export const FETCH_LIST_CHAPTER_SUCCESS_ACTION = 'FETCH_LIST_CHAPTER_SUCCESS_ACTION';
export const FETCH_LIST_CHAPTER_FAILD_ACTION = 'FETCH_LIST_CHAPTER_FAILD_ACTION';
export const FETCH_LIST_SUBJECT_START_ACTION = 'FETCH_LIST_SUBJECT_START_ACTION';
export const FETCH_LIST_SUBJECT_SUCCESS_ACTION = 'FETCH_LIST_SUBJECT_SUCCESS_ACTION';
export const FETCH_LIST_SUBJECT_FAILD_ACTION = 'FETCH_LIST_SUBJECT_FAILD_ACTION';
export const FETCH_RECENT_START_ACTION = 'FETCH_RECENT_START_ACTION';
export const FETCH_RECENT_SUCCESS_ACTION = 'FETCH_RECENT_SUCCESS_ACTION';
export const FETCH_RECENT_FAILD_ACTION = 'FETCH_RECENT_FAILD_ACTION';
export const FETCH_LIST_EXECISE_START_ACTION = 'FETCH_LIST_EXECISE_START_ACTION';
export const FETCH_LIST_EXECISE_SUCCESS_ACTION = 'FETCH_LIST_EXECISE_SUCCESS_ACTION';
export const FETCH_LIST_EXECISE_FAILD_ACTION = 'FETCH_LIST_EXECISE_FAILD_ACTION';
export const FETCH_REPORT_START_ACTION = 'FETCH_REPORT_START_ACTION';
export const FETCH_REPORT_SUCCESS_ACTION = 'FETCH_REPORT_SUCCESS_ACTION';
export const FETCH_REPORT_FAILD_ACTION = 'FETCH_REPORT_FAILD_ACTION';
export const FETCH_LIST_GRADE_ACTION = 'FETCH_LIST_GRADE_ACTION';
export const FETCH_LIST_GRADE_SUCCESS_ACTION = 'FETCH_LIST_GRADE_SUCCESS_ACTION';
export const FETCH_LIST_GRADE_FAILD_ACTION = 'FETCH_LIST_GRADE_FAILD_ACTION';
export const FETCH_LIST_BOOKMARK_HIEARY_ACTION = 'FETCH_LIST_BOOKMARK_HIEARY_ACTION';
export const FETCH_LIST_BOOKMARK_MORE_HIEARY_ACTION = 'FETCH_LIST_BOOKMARK_MORE_HIEARY_ACTION';
export const FETCH_LIST_BOOKMARK_SUCCESS_ACTION = 'FETCH_LIST_BOOKMARK_SUCCESS_ACTION';
export const FETCH_LIST_BOOKMARK_FAILD_ACTION = 'FETCH_LIST_BOOKMARK_FAILD_ACTION';
export const FETCH_LIST_PROCESS_ACTION = 'FETCH_LIST_PROCESS_ACTION';
export const FETCH_LIST_PROCESS_MORE_ACTION = 'FETCH_LIST_PROCESS_MORE_ACTION';
export const FETCH_LIST_PROCESS_SUCCESS_ACTION = 'FETCH_LIST_PROCESS_SUCCESS_ACTION';
export const FETCH_LIST_PROCESS_FAILD_ACTION = 'FETCH_LIST_PROCESS_FAILD_ACTION';
export const FETCH_TARGET_START_ACTION = 'FETCH_TARGET_START_ACTION';
export const FETCH_TARGET_SUCCESS_ACTION = 'FETCH_TARGET_SUCCESS_ACTION';
export const FETCH_TARGET_FAILD_ACTION = 'FETCH_TARGET_FAILD_ACTION';
export const FETCH_LIST_SLA_INFO_ACTION = 'FETCH_LIST_SLA_INFO_ACTION';
export const FETCH_LIST_SLA_INFO_SUCCESS_ACTION = 'FETCH_LIST_SLA_INFO_SUCCESS_ACTION';
export const FETCH_LIST_SLA_INFO_FAILD_ACTION = 'FETCH_LIST_SLA_INFO_FAILD_ACTION';
export const FETCH_CATEGORY_ACTION = 'FETCH_CATEGORY_ACTION';
export const FETCH_CATEGORY_MORE_ACTION = 'FETCH_CATEGORY_MORE_ACTION';
export const FETCH_CATEGORY_SUCCESS_ACTION = 'FETCH_CATEGORY_SUCCESS_ACTION';
export const FETCH_CATEGORY_FAILD_ACTION = 'FETCH_CATEGORY_FAILD_ACTION';
export const FETCH_CATEGORY_LEVEL_ACTION = 'FETCH_CATEGORY_LEVEL_ACTION';
export const FETCH_CATEGORY_LEVEL_SUCCESS_ACTION = 'FETCH_CATEGORY_LEVEL_SUCCESS_ACTION';
export const FETCH_CATEGORY_LEVEL_FAILD_ACTION = 'FETCH_CATEGORY_LEVEL_FAILD_ACTION';
export const FETCH_CATEGORY_DETAIL_ACTION = 'FETCH_CATEGORY_DETAIL_ACTION';
export const FETCH_CATEGORY_DETAIL_SUCCESS_ACTION = 'FETCH_CATEGORY_DETAIL_SUCCESS_ACTION';
export const FETCH_CATEGORY_DETAIL_FAILD_ACTION = 'FETCH_CATEGORY_DETAIL_FAILD_ACTION';
export const FETCH_CATEGORY_TIME_ACTION = 'FETCH_CATEGORY_TIME_ACTION';
export const FETCH_CATEGORY_TIME_SUCCESS_ACTION = 'FETCH_CATEGORY_TIME_SUCCESS_ACTION';
export const FETCH_CATEGORY_TIME_FAILD_ACTION = 'FETCH_CATEGORY_TIME_FAILD_ACTION';
export const FETCH_DATA_PRACTICE_ACTION = 'FETCH_DATA_PRACTICE_ACTION';
export const FETCH_DATA_PRACTICE_SUCCESS_ACTION = 'FETCH_DATA_PRACTICE_SUCCESS_ACTION';
export const FETCH_DATA_PRACTICE_FAILD_ACTION = 'FETCH_DATA_PRACTICE_FAILD_ACTION';
export const FETCH_ANSWER_QUESTION_ACTION = 'FETCH_ANSWER_QUESTION_ACTION';
export const FETCH_ANSWER_QUESTION_SUCCESS_ACTION = 'FETCH_ANSWER_QUESTION_SUCCESS_ACTION';
export const FETCH_ANSWER_QUESTION_FAILD_ACTION = 'FETCH_ANSWER_QUESTION_FAILD_ACTION';
export const FETCH_LIST_SLA_SUBJECT_ACTION = 'FETCH_LIST_SLA_SUBJECT_ACTION';
export const FETCH_LIST_SLA_SUBJECT_SUCCESS_ACTION = 'FETCH_LIST_SLA_SUBJECT_SUCCESS_ACTION';
export const FETCH_LIST_SLA_SUBJECT_FAILD_ACTION = 'FETCH_LIST_SLA_SUBJECT_FAILD_ACTION';
export const FETCH_LIST_PRACTICE_SUBJECT_ACTION = 'FETCH_LIST_PRACTICE_SUBJECT_ACTION';
export const FETCH_LIST_PRACTICE_SUBJECT_SUCCESS_ACTION = 'FETCH_LIST_PRACTICE_SUBJECT_SUCCESS_ACTION';
export const FETCH_LIST_PRACTICE_SUBJECT_FAILD_ACTION = 'FETCH_LIST_PRACTICE_SUBJECT_FAILD_ACTION';
export const FETCH_TEST_SLA_DETAIL_DONE_ACTION = 'FETCH_TEST_SLA_DETAIL_DONE_ACTION';
export const FETCH_TEST_SLA_DETAIL_DONE_SUCCESS_ACTION = 'FETCH_TEST_SLA_DETAIL_DONE_SUCCESS_ACTION';
export const FETCH_TEST_SLA_DETAIL_DONE_FAILD_ACTION = 'FETCH_TEST_SLA_DETAIL_DONE_FAILD_ACTION';
export const FETCH_PRACTICE_SLA_START_ACTION = 'FETCH_PRACTICE_SLA_START_ACTION';
export const FETCH_PRACTICE_SLA_SUCCESS_ACTION = 'FETCH_PRACTICE_SLA_SUCCESS_ACTION';
export const FETCH_PRACTICE_SLA_FAILD_ACTION = 'FETCH_PRACTICE_SLA_FAILD_ACTION';
export const FETCH_RECENT_SLA_ACTION = 'FETCH_RECENT_SLA_ACTION';
export const FETCH_RECENT_SLA_SUCCESS_ACTION = 'FETCH_RECENT_SLA_SUCCESS_ACTION';
export const FETCH_RECENT_SLA_FAILD_ACTION = 'FETCH_RECENT_SLA_FAILD_ACTION';
export const FETCH_TEST_SLA_DETAIL_START_ACTION = 'FETCH_TEST_SLA_DETAIL_START_ACTION';
export const FETCH_TEST_SLA_DETAIL_SUCCESS_ACTION = 'FETCH_TEST_SLA_DETAIL_SUCCESS_ACTION';
export const FETCH_TEST_SLA_DETAIL_FAILD_ACTION = 'FETCH_TEST_SLA_DETAIL_FAILD_ACTION';
export const FETCH_USER_INFOMTAION_ACTION = 'FETCH_USER_INFOMTAION_ACTION';
export const FETCH_USER_INFOMTAION_SUCCESS_ACTION = 'FETCH_USER_INFOMTAION_SUCCESS_ACTION';
export const FETCH_USER_INFOMTAION_FAILD_ACTION = 'FETCH_USER_INFOMTAION_FAILD_ACTION';
export const FETCH_STATISTIC_CHART_ACTION = 'FETCH_STATISTIC_CHART_ACTION';
export const FETCH_STATISTIC_CHART_SUCCESS_ACTION = 'FETCH_STATISTIC_CHART_SUCCESS_ACTION';
export const FETCH_STATISTIC_CHART_FAILD_ACTION = 'FETCH_STATISTIC_CHART_FAILD_ACTION';
export const FETCH_MATERY_USER_START_ACTION = 'FETCH_MATERY_USER_START_ACTION';
export const FETCH_MATERY_USER_SUCCESS_ACTION = 'FETCH_MATERY_USER_SUCCESS_ACTION';
export const FETCH_MATERY_USER_FAILD_ACTION = 'FETCH_MATERY_USER_FAILD_ACTION';
export const UPDATE_USER_PROFILE_ACTION = 'UPDATE_USER_PROFILE_ACTION';
export const UPDATE_USER_PROFILE_SUCCESS_ACTION = 'UPDATE_USER_PROFILE_SUCCESS_ACTION';
export const UPDATE_USER_PROFILE_FAILD_ACTION = 'UPDATE_USER_PROFILE_FAILD_ACTION';
export const CHANGE_PASSWORD_ACTION = 'CHANGE_PASSWORD_ACTION';
export const CHANGE_PASSWORD_SUCCESS_ACTION = 'CHANGE_PASSWORD_SUCCESS_ACTION';
export const CHANGE_PASSWORD_FAILD_ACTION = 'CHANGE_PASSWORD_FAILD_ACTION';
export const NAVIGATION_NAVIGATE_ROOT_ACTION = 'NAVIGATION_NAVIGATE_ROOT_ACTION';
export const NAVIGATION_NAVIGATE_SUBJECT_ACTION = 'NAVIGATION_NAVIGATE_SUBJECT_ACTION';
export const NAVIGATION_NAVIGATE_PRACTICE_ACTION = 'NAVIGATION_NAVIGATE_PRACTICE_ACTION';
export const NAVIGATION_NAVIGATE_GRADE_CHANGE_ACTION = 'NAVIGATION_NAVIGATE_GRADE_CHANGE_ACTION';
export const NAVIGATION_NAVIGATE_LEARN_ACTION = 'NAVIGATION_NAVIGATE_LEARN_ACTION';
export const NAVIGATION_NAVIGATE_CATEGORY_ACTION = 'NAVIGATION_NAVIGATE_CATEGORY_ACTION';
export const NAVIGATION_NAVIGATE_CATEGORY_DETAIL_ACTION = 'NAVIGATION_NAVIGATE_CATEGORY_DETAIL_ACTION';
export const NAVIGATION_NAVIGATE_BOOKMARK_ACTION = 'NAVIGATION_NAVIGATE_BOOKMARK_ACTION';
export const NAVIGATION_NAVIGATE_BOOKMARK_DETAIL_ACTION = 'NAVIGATION_NAVIGATE_BOOKMARK_DETAIL_ACTION';
export const NAVIGATION_NAVIGATE_CATE_LEVEL_ACTION = 'NAVIGATION_NAVIGATE_CATE_LEVEL_ACTION';
export const NAVIGATION_NAVIGATE_CATE_TIME_ACTION = 'NAVIGATION_NAVIGATE_CATE_TIME_ACTION';
export const NAVIGATION_NAVIGATE_GOBACK_ACTION = 'NAVIGATION_NAVIGATE_GOBACK_ACTION';
export const NAVIGATION_NAVIGATE_VIDEO_ACTION = 'NAVIGATION_NAVIGATE_VIDEO_ACTION';
export const NAVIGATION_NAVIGATE_TARGET_ACTION = 'NAVIGATION_NAVIGATE_TARGET_ACTION';
export const NAVIGATION_NAVIGATE_SLA_INFO_ACTION = 'NAVIGATION_NAVIGATE_SLA_INFO_ACTION';
export const NAVIGATION_NAVIGATE_PAYMENT_UPGRADE = 'NAVIGATION_NAVIGATE_PAYMENT_UPGRADE';
export const NAVIGATION_NAVIGATE_CHAPTER_SLA = 'NAVIGATION_NAVIGATE_CHAPTER_SLA';
export const NAVIGATION_NAVIGATE_GO_AUTH_ACTION = 'NAVIGATION_NAVIGATE_GO_AUTH_ACTION';
export const NAVIGATION_NAVIGATE_GO_HOME_WORK_ACTION = 'NAVIGATION_NAVIGATE_GO_HOME_WORK_ACTION';
export const NAVIGATION_NAVIGATE_GO_SCHOOL_RESULTAB = "NAVIGATION_NAVIGATE_GO_SCHOOL_RESULTAB";
export const NAVIGATION_NAVIGATE_GO_CLASS_STUDENT_TAB = "NAVIGATION_NAVIGATE_GO_CLASS_STUDENT_TAB";
export const NAVIGATION_NAVIGATE_GO_TO_HOMEWORKDRAWER = "NAVIGATION_NAVIGATE_GO_TO_HOMEWORKDRAWER";
export const NVAIGATION_NAVIGATE_GO_TO_LIST_EXAM = "NVAIGATION_NAVIGATE_GO_TO_LIST_EXAM";
export const NVAIGATION_NAVIGATE_GO_TO_UPGRADE_STEP = "NVAIGATION_NAVIGATE_GO_TO_UPGRADE_STEP";

export const SET_PROFILE_USER_ACTION = 'SET_PROFILE_USER_ACTION';
export const SET_GRADE_ID_ACTION = 'SET_GRADE_ID_ACTION';
export const UPGRADE_PHONE_NOW_ACTION = 'UPGRADE_PHONE_NOW_ACTION';
export const CHONSE_ANSWER_SELECT_ACTION = 'CHONSE_ANSWER_SELECT_ACTION';

export const FETCH_LIST_CLASS_OF_USER_ACTION = 'FETCH_LIST_CLASS_OF_USER_ACTION';
export const FETCH_LIST_CLASS_OF_USER_SUCCESS_ACTION = 'FETCH_LIST_CLASS_OF_USER_SUCCESS_ACTION';
export const FETCH_LIST_CLASS_OF_USER_FAILD_ACTION = 'FETCH_LIST_CLASS_OF_USER_FAILD_ACTION';

export const FETCH_LIST_HOMEWORK_ACTION = 'FETCH_LIST_HOMEWORK_ACTION';
export const FETCH_LIST_HOMEWORK_SUCCESS_ACTION = 'FETCH_LIST_HOMEWORK_SUCCESS_ACTION';
export const FETCH_LIST_HOMEWORK_FAILD_ACTION = 'FETCH_LIST_HOMEWORK_FAILD_ACTION';

export const FETCH_INFO_ASSIGNMENT_ACTION = 'FETCH_INFO_ASSIGNMENT_ACTION';
export const FETCH_INFO_ASSIGNMENT_SUCCESS_ACTION = 'FETCH_INFO_ASSIGNMENT_SUCCESS_ACTION';
export const FETCH_INFO_ASSIGNMENT_FAILD_ACTION = 'FETCH_INFO_ASSIGNMENT_FAILD_ACTION';

export const FETCH_RESULT_DETAIL_ACTION = 'FETCH_RESULT_DETAIL_ACTION';
export const FETCH_RESULT_DETAIL_SUCCESS_ACTION = 'FETCH_RESULT_DETAIL_SUCCESS_ACTION';
export const FETCH_RESULT_DETAIL_FAILD_ACTION = 'FETCH_RESULT_DETAIL_FAILD_ACTION';

export const FETCH_CREATE_ASSIGNMENT_ACTION = 'FETCH_CREATE_ASSIGNMENT_ACTION';
export const FETCH_CREATE_ASSIGNMENT_SUCCESS_ACTION = 'FETCH_CREATE_ASSIGNMENT_SUCCESS_ACTION';
export const FETCH_CREATE_ASSIGNMENT_FAILD_ACTION = 'FETCH_CREATE_ASSIGNMENT_FAILD_ACTION';

export const FETCH_LIST_TITLE_QUESTION_ACTION = 'FETCH_LIST_TITLE_QUESTION_ACTION';
export const FETCH_LIST_TITLE_QUESTION_SUCCESS_ACTION = 'FETCH_LIST_TITLE_QUESTION_SUCCESS_ACTION';
export const FETCH_LIST_TITLE_QUESTION_FAILD_ACTION = 'FETCH_LIST_TITLE_QUESTION_FAILD_ACTION';

export const FETCH_CONTENT_QUESSTION_ACTION = 'FETCH_CONTENT_QUESSTION_ACTION';
export const FETCH_CONTENT_QUESSTION_SUCCESS_ACTION = 'FETCH_CONTENT_QUESSTION_SUCCESS_ACTION';
export const FETCH_CONTENT_QUESSTION_FAILD_ACTION = 'FETCH_CONTENT_QUESSTION_FAILD_ACTION';

export const FETCH_CHART_BUY_SUBJECT_ID_ACTION = 'FETCH_CHART_BUY_SUBJECT_ID_ACTION';
export const FETCH_CHART_BUY_SUBJECT_ID_SUCCESS_ACTION = 'FETCH_CHART_BUY_SUBJECT_ID_SUCCESS_ACTION';
export const FETCH_CHART_BUY_SUBJECT_ID_FAILD_ACTION = 'FETCH_CHART_BUY_SUBJECT_ID_FAILD_ACTION';

export const FETCH_CHART_CONTRIBUTION_ACTION = 'FETCH_CHART_CONTRIBUTION_ACTION';
export const FETCH_CHART_CONTRIBUTION_SUCCESS_ACTION = 'FETCH_CHART_CONTRIBUTION_SUCCESS_ACTION';
export const FETCH_CHART_CONTRIBUTION_FAILD_ACTION = 'FETCH_CHART_CONTRIBUTION_FAILD_ACTION';

export const FETCH_FLASH_CARD_THEORY_ACTION = 'FETCH_FLASH_CARD_THEORY_ACTION';
export const FETCH_FLASH_CARD_THEORY_SUCCESS_ACTION = 'FETCH_FLASH_CARD_THEORY_SUCCESS_ACTION';
export const FETCH_FLASH_CARD_THEORY_FAILD_ACTION = 'FETCH_FLASH_CARD_THEORY_FAILD_ACTION';

export const FETCH_FLASH_CARD_VIDEO_ACTION = 'FETCH_FLASH_CARD_VIDEO_ACTION';
export const FETCH_FLASH_CARD_VIDEO_SUCCESS_ACTION = 'FETCH_FLASH_CARD_VIDEO_SUCCESS_ACTION';
export const FETCH_FLASH_CARD_VIDEO_FAILD_ACTION = 'FETCH_FLASH_CARD_VIDEO_FAILD_ACTION';

export const FETCH_LIST_MOCK_EXAM_ACTION = 'FETCH_LIST_MOCK_EXAM_ACTION';
export const FETCH_LIST_MOCK_EXAM_SUCCESS_ACTION = 'FETCH_LIST_MOCK_EXAM_SUCCESS_ACTION';
export const FETCH_LIST_MOCK_EXAM_FAILD_ACTION = 'FETCH_LIST_MOCK_EXAM_FAILD_ACTION';

export const FETCH_DETAIL_MOCK_EXAM_ACTION = 'FETCH_DETAIL_MOCK_EXAM_ACTION';
export const FETCH_DETAIL_MOCK_EXAM_SUCCESS_ACTION = 'FETCH_DETAIL_MOCK_EXAM_SUCCESS_ACTION';
export const FETCH_DETAIL_MOCK_EXAM_FAILD_ACTION = 'FETCH_DETAIL_MOCK_EXAM_FAILD_ACTION';

export const SAVE_AVATAR_ACTION = 'SAVE_AVATAR_ACTION';
export const SAVE_USER_ACTION = 'SAVE_USER_ACTION';

export const FETCH_DATA_HOMEWORK_TEACHER_ACTION = 'FETCH_DATA_HOMEWORK_TEACHER_ACTION';
export const FETCH_DATA_HOMEWORK_TEACHER_SUCCESS_ACTION = 'FETCH_DATA_HOMEWORK_TEACHER_SUCCESS_ACTION';
export const FETCH_DATA_HOMEWORK_TEACHER_FAILED_ACTION = 'FETCH_DATA_HOMEWORK_TEACHER_FAILED_ACTION';

export const FETCH_DATA_REPORT_ACTION = 'FETCH_DATA_REPORT_ACTION';
export const FETCH_DATA_REPORT_SUCCESS_ACTION = 'FETCH_DATA_REPORT_SUCCESS_ACTION';
export const FETCH_DATA_REPORT_FAILED_ACTION = 'FETCH_DATA_REPORT_FAILED_ACTION';

export const FETCH_ASSIGNMENT_DETAIL_ACTION = 'FETCH_ASSIGNMENT_DETAIL_ACTION';
export const FETCH_ASSIGNMENT_DETAIL_SUCCESS_ACTION = 'FETCH_ASSIGNMENT_DETAIL_SUCCESS_ACTION';
export const FETCH_ASSIGNMENT_DETAIL_FAILED_ACTION = 'FETCH_ASSIGNMENT_DETAIL_FAILED_ACTION';

export const SAVE_LIST_GRADES = 'SAVE_LIST_GRADES';
export const SAVE_LIST_SUBJECT = 'SAVE_LIST_SUBJECT';

export const FETCH_COMMON_SUBJECT_MISSION = 'FETCH_COMMON_SUBJECT_MISSION';
export const FETCH_COMMON_SUBJECT_MISSION_SUCCESS = 'FETCH_COMMON_SUBJECT_MISSION_SUCCESS';

export const FETCH_LIST_MISSION = 'FETCH_LIST_MISSION';
export const FETCH_LIST_MISSION_SUCCESS = 'FETCH_LIST_MISSION_SUCCESS';

export const FETCH_CATEGORY_HIRACHY_MISSION = 'FETCH_CATEGORY_HIRACHY_MISSION';
export const FETCH_CATEGORY_HIRACHY_MISSION_SUCCESS = 'FETCH_CATEGORY_HIRACHY_MISSION_SUCCESS';

export const FETCH_CATEGORY_TEST_MISSION = 'FETCH_CATEGORY_TEST_MISSION';
export const FETCH_CATEGORY_TEST_MISSION_SUCCESS = 'FETCH_CATEGORY_TEST_MISSION_SUCCESS';

export const FETCH_LIST_PROBLEM_MISSION = 'FETCH_LIST_PROBLEM_MISSION';
export const FETCH_LIST_PROBLEM_MISSION_SUCCESS = 'FETCH_LIST_PROBLEM_MISSION_SUCCESS';

export const FETCH_LIST_PROBLEM_TEST_MISSION = 'FETCH_LIST_PROBLEM_TEST_MISSION';
export const FETCH_LIST_PROBLEM_TEST_MISSION_SUCCESS = 'FETCH_LIST_PROBLEM_TEST_MISSION_SUCCESS';

export const FETCH_ASSIGNMENT_BY_MISSION = 'FETCH_ASSIGNMENT_BY_MISSION';
export const FETCH_ASSIGNMENT_BY_MISSION_SUCCESS = 'FETCH_ASSIGNMENT_BY_MISSION_SUCCESS';

export const RESET_DATA_MISSION = 'RESET_DATA_MISSION';

export const NEED_UPDATE_EXAM_LIST_ACTION ='NEED_UPDATE_EXAM_LIST_ACTION';