module.exports = {
  idItemMockExam: '',
  onSignIn: null,
  onStartTimeHocmai: null,
  hideDrawerMenu: null,
  onNavigationChange: null,
  setModalVisible: null,
  setModalReviewVisible: null,
  setModalWarning: null,
  mPauseVisible: null,
  showModalPause: null,
  showSubjectView: null,
  loadSubjectSuccess: null,
  updateExam: null,
  updateGrades: null,
  updateDataChange: null,
  updateBookMark: null,
  updateExamSla: null,
  updateTest: null,
  updateListQuestionSla: null,
  updateListQuestionTest: null,
  updateRecent: null,
  updateSla: null,
  updatePractice: null,
  updateSlaTab: null,
  updateReport: null,
  updateAction: null,
  updateProcess: null,
  updateQuestion: null,
  onHandleMessage: null,
  slideInLeftStart: null,
  slideInLeft2Start: null,
  opacityOutStart: null,
  opacityOut2Start: null,
  showModalReview: null,
  learnVideo: null,
  onMessageBM: null,
  onMessageReview: null,
  handleMessageMain: null,
  onHandleMessage: null,
  onHandlePracticeMessage: null,
  onHandleMessageExamSla: null,
  updateRemember: null,
  updateProblem: null,
  updateProblemDetail: null,
  updateAvatar: null,
  updateUserInfo: null,
  updateTestHome: null,
  updatePracticeHome: null,
  updateListQuestionHomework: null,
  subjectName: null,
  subjectId: null,
  ratioImageBottom: 162 / 375,
  updateListHomework: null,
  getDataExamListSubject: null,
  handleTimeout: null,
  getDataExamGroup: null,
  updateDataCompetition: null,
  nameCompetition: '',
  updateDataCompetitionStep: null,
  timeEndInListHomeWork: null,
  permissionViewResult: null,
  updateQuestionMockExam: () => { },
  updateMenuQuestion: () => { },
  nextQuestion: () => { },
  updatePlan: () => { },
  updatePaper: () => { },
  updateHomeWork: () => { },
};
